# Generated by Django 2.2.6 on 2019-10-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer_score',
        ),
    ]
